### ISSUE TITLE
Error: Mnemonic invalid or undefined - when running truffle develop and migrate

### ISSUE THREAD

**Issue by figs999** [trufflesuite/truffle#1581]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

After upgrading my installation of truffle to v5, I ran truffle init on an existing project, maintaining all folders contents, but allowing my projects config to be overwritten with the new version's boilerplate.

After this, when running truffle develop and truffle migrate I receive the following error:

> Error: Mnemonic invalid or undefined
>     at new v (C:\Users\Chance\Desktop\taptrust-wallet-contracts\node_modules\truffle-hdwallet-provider\dist\webpack:\truffle-hdwallet-provider\src\index.js:51:1)
>     at Object.<anonymous> (C:\Users\Chance\Desktop\taptrust-wallet-contracts\truffle.js:37:17)
>     at Module._compile (module.js:652:30)

I spoke with @gnidan on gitter and he worked with me to attempt to find a solution.
The following steps were taken:
- Checked the truffle module's config.json, it was empty
- Installed truffle-core, and ran require('truffle-core/lib/mnemonics/mnemonic').getOrGenerateMnemonic()
- This threw: "Error: Cannot find module 'bip39'"
- Installed bip39 module and re-ran above command
- This functioned correctly, and populated my config.json with a mnemonic
- Truffle develop still failed to run
- Attempted to run ./node_modules/truffle-core/cli.js develop, but it had the same failure
- Ran require('truffle-core/lib/mnemonics/mnemonic').getAccountsInfo(10), which correctly showed accounts associated with the saved mnemonic
- At this point @gnidan had to sign-off and suggested I open this Issue.

## Steps to Reproduce

Unknown, as other users seem to have been able to upgrade without issue.

## Expected Behavior

truffle develop and truffle migrate should generate a new mnemonic automatically if one is not present.

## Actual Results

truffle develop and truffle migrate throw errors when run

## Environment

* Operating System: Windows
* Ethereum client: none (using truffle develop)
* Truffle version (`truffle version`): v5
* node version (`node --version`): v8.11.3
* npm version (`npm --version`): 5.6.0

**Comment by figs999** [comment]
I'm actually going to suggest you close this issue. After downgrading to truffle 4 and then upgrading to truffle 5 again, the issue disappeared and I can no longer repro it.

**Comment by eggplantzzz** [comment]
Well I guess that is good enough! Closing.

**Comment by Betochoa** [comment]
Hi so I didn`t quite get how this was solved... Should I just downgrade and ugrade?

**Comment by kigh143** [comment]
hello, I am getting this error. what is the solution again. I don't seem to get what the solution is from here.

**Comment by SumanChakraborty1998** [comment]
I am also not getting the solution. What seems to be done

**Comment by cds-amal** [comment]
Hi @SumanChakraborty1998, please open a [new issue](https://github.com/trufflesuite/truffle/issues/new), so we can track and resolve it.
