### PR TITLE
Dependency update: Upgrade dependency: web3@1.7.1

### PR DESCRIPTION
**Pull request by eggplantzzz**
This PR upgrades web3 and it's subpackages to 1.7.3.

* @truffle/artifactor: 1.5.3 →  1.7.3
* @truffle/contract: 1.5.3 →  1.7.3
* @truffle/contract-tests: 1.5.3 →  1.7.3
* @truffle/core: 1.5.3 →  1.7.3
* @truffle/dashboard-provider: ^1.6.1 →  1.7.3
* @truffle/db: 1.5.3 →  1.7.3
* @truffle/debugger: 1.5.3 →  1.7.3
* @truffle/decoder: 1.5.3 →  1.7.3
* @truffle/deployer: 1.5.3 →  1.7.3
* @truffle/encoder: 1.5.3 →  1.7.3
* @truffle/environment: 1.5.3 →  1.7.3
* @truffle/hdwallet-provider: 1.5.3 →  1.7.3
* @truffle/interface-adapter: 1.5.3 →  1.7.3
* @truffle/provider: 1.5.3 →  1.7.3
* truffle: 1.5.3 →  1.7.3

### CODE REVIEW

**Comment by wbt** [comment]
@eggplantzzz Might we be able to reopen and potentially merge a version that goes to 1.7.4, or were there particular reasons for this to be closed?

After running an `npm audit fix` I'm now running into a TypeScript compilation error where the BN types used in some parts of the application are incompatible with the BN types used elsewhere, because the older version of web3 is still using @types/bn.js@4.11.6 while newer versions are using @types/bn.js@^5.1.0.  It looks like the change was [in this commit](https://github.com/ChainSafe/web3.js/commit/23e3045cdd54421ede10b3633d39e1a5576ee790) just 14 days ago in [this PR](https://github.com/ChainSafe/web3.js/pull/5074), released [yesterday](https://github.com/ChainSafe/web3.js/pull/5036).

It was another one of those breaking-change-on-nonbreaking-semver that I had earnestly-but-in-vain hoped this cluster of projects had gotten away from. However, I think at Truffle bumping all web3 dependencies to 1.7.4 would likely bring things back into consistency at least for me.

**Comment by cds-amal** [comment]
Hey @wbt we ran into issues with our tests when upgrading to 1.7.1 and currently have a [branch working to sort out those issues](https://github.com/trufflesuite/truffle/pull/5177).

**Comment by wbt** [comment]
OK, I subscribed to that.  With the web3 release out yesterday not being marked as a breaking change, resolving this has suddenly become an urgent blocker for me and probably for others too who just haven't figured out what's going on yet.
