### ISSUE TITLE
v3.3.0 regression in handling 'require'

### ISSUE THREAD

**Issue by area** [trufflesuite/truffle#465]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Projects that `require` node modules in migrations work on 3.2.5 but do not work on 3.3.0.

## Steps to Reproduce
With testrpc running, in a new directory:
```
truffle init
npm init -f
npm install --save assert
echo -e "var assert = require('assert')\n$(cat ./migrations/2_deploy_contracts.js)" > ./migrations/2_deploy_contracts.js
truffle test
```
## Expected Behavior

The tests should run as expected. Output with Truffle 3.2.5:
```
 truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...


  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (124ms)
    ✓ testInitialBalanceWithNewMetaCoin (120ms)

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account (42ms)
    ✓ should call a function that depends on a linked library (115ms)
    ✓ should send coin correctly (216ms)


  5 passing (1s)
```
## Actual Results
```
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...
~/.nvm/versions/node/v7.4.0/lib/node_modules/truffle/build/cli.bundled.js:85871
            return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
                                                                                                                                   ^

Error: Cannot find module "."
    at webpackMissingModule (~/.nvm/versions/node/v7.4.0/lib/node_modules/truffle/build/cli.bundled.js:85871:64)
    at require (~/.nvm/versions/node/v7.4.0/lib/node_modules/truffle/build/cli.bundled.js:85871:142)
    at ~/truffle-issue/migrations/2_deploy_contracts.js:1:14
    at ContextifyScript.Script.runInContext (vm.js:37:29)
    at ContextifyScript.Script.runInNewContext (vm.js:43:15)
    at ~/.nvm/versions/node/v7.4.0/lib/node_modules/truffle/build/cli.bundled.js:85890:14
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```
## Environment

* Operating System: OSX El Capitan
* Truffle version: 3.3.0
* Ethereum client: Testrpc v4.0.0
* node version: 7.4
* npm version: 4.0.5

**Comment by jdkanani** [comment]
Same happens in external script "truffle exec"!

**Comment by luando** [comment]
I have same error with command "truffle exec"

**Comment by tcoulter** [comment]
This should be fixed in v3.4.3. Let me know if you run into any issues.
