### ISSUE TITLE
Solc Version not working, not reading the solc version in truffle-config.js file

### ISSUE THREAD

**Issue by Tedmcm** [trufflesuite/truffle#4109]
- [ yes, for 12 days ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Im working on a project and the contracts use multiple solc versions and when I had to redeploy the contracts in a different order than originally deployed due to a deployment issue truffle has gotten stuck on a certain solc version, in my truffle-config.js file it says version 0.6.12, in the package.json file it says 0.6.12 but when i run either truffle compile or migrate --reset --network ropsten it says 0.5.16 and no matter what i do it wont go off that version, i have un installed solc, truffle and re installed a number of times and nothing will change it.. 

truffle-config.js    file. 
----------------------------------------------------
/**
 * Use this file to configure your truffle project. It's seeded with some
 * common settings for different networks and features like migrations,
 * compilation and testing. Uncomment the ones you need or modify
 * them to suit your project as necessary.
 *
 * More information about configuration can be found at:
 *
 * trufflesuite.com/docs/advanced/configuration
 *
 * To deploy via Infura you'll need a wallet provider (like @truffle/hdwallet-provider)
 * to sign your transactions before they're sent to a remote public node. Infura accounts
 * are available for free at: infura.io/register.
 *
 * You'll also need a mnemonic - the twelve word phrase the wallet uses to generate
 * public/private key pairs. If you're publishing your code to GitHub make sure you load this
 * phrase from a file you've .gitignored so it doesn't accidentally become public.
 *
 */
const fs = require('fs');
const HDWalletProvider = require('@truffle/hdwallet-provider');
// const infuraKey = "fj4jll3k.....";
//

require('events').EventEmitter.prototype._maxListeners = 70;
require('events').defaultMaxListeners = 70;

// const fs = require('fs');
// const mnemonic = fs.readFileSync(".secret").toString().trim();
const secrets = JSON.parse(
  fs.readFileSync('secrets').toString().trim()
);
// truffle-HDWallet-provider
// https://ropsten.infura.io/v3/
module.exports = {
  /**
   * Networks define how you connect to your ethereum client and let you set the
   * defaults web3 uses to send transactions. If you don't specify one truffle
   * will spin up a development blockchain for you on port 9545 when you
   * run `develop` or `test`. You can ask a truffle command to use a specific
   * network from the command line, e.g
   *
   * $ truffle test --network <network-name>
   */
   plugins: [
    'truffle-plugin-verify'
  ],

    api_keys: {
    etherscan: ''
  },

  networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache-cli, geth or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    // development: {
    //  host: "127.0.0.1",     // Localhost (default: none)
    //  port: 8545,            // Standard Ethereum port (default: none)
    //  network_id: "*",       // Any network (default: none)
    // },
    // Another network with more advanced options...
    // advanced: {
    // port: 8777,             // Custom port
    // network_id: 1342,       // Custom network
    // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
    // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
    // from: <address>,        // Account to send txs from (default: accounts[0])
    // websocket: true        // Enable EventEmitter interface for web3 (default: false)
    // },
    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    //Can use mnumonic save in ENV
     ropsten: {
     provider: () => new HDWalletProvider(secrets.seed, `https://ropsten.infura.io/v3/${secrets.projectId}`),
      network_id: 3,       // Ropsten's id
    // gas: 5500000,        // Ropsten has a lower block limit than mainnet
    // confirmations: 2,    // # of confs to wait between deployments. (default: 0)
    // timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
     skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
     }
    // Useful for private networks
    // private: {
    // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
     }
  };

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  };

  // Configure your compilers
  compilers: {
    solc: {
       version: "^0.6.12"    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  };

  // Truffle DB is currently disabled by default; to enable it, change enabled: false to enabled: true
  //
  // Note: if you migrated your contracts prior to enabling this field in your Truffle project and want
  // those previously migrated contracts available in the .db directory, you will need to run the following:
  // $ truffle migrate --reset --compile-all

  db: {
    enabled: false
  }
-----------------------------------------------------------------------------

This is the package.json file 

This is the package.json file dependancies...
"dependencies": {
    "solc": "^0.6.12"
  }
}
---------------------------------------------------------------------------
So in both places it says use 0.6.12 but when i try to compile or truffle migrate --reset --network ropsten 
it doesnt work.. All i get back is this....

----------------------------------------------------------------------------------
this is what i get from migrate --reset --network ropsten

/Users/edwardmcmillan/bull_bear_dex/contracts/GovernorAlpha.sol:13:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/MasterChef.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/MasterChefV2.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/Migrator.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/MiniChefV2.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/Ownable.sol:5:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/SushiBar.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/SushiMaker.sol:4:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/SushiMakerKashi.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/SushiRoll.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/SushiToken.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/WETH.sol:20:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/bentobox/BentoBoxV1.sol:19:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/bentobox/KashiPairMediumRiskV1.sol:18:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/bentobox/PeggedOracleV1.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/governance/Timelock.sol:14:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/interfaces/IERC20.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/interfaces/IMasterChef.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/interfaces/IMiniChefV2.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/interfaces/IRewarder.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/libraries/SafeERC20.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/libraries/SafeMath.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/libraries/SignedSafeMath.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/ComplexRewarder.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/ComplexRewarderTime.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/ERC20Mock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/RewarderBrokenMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/RewarderMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/SushiMakerExploitMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/SushiMakerKashiExploitMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/SushiSwapFactoryMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/SushiSwapPairMock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/mocks/WETH9Mock.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.6.12;
^---------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/UniswapV2ERC20.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/UniswapV2Factory.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/UniswapV2Pair.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/UniswapV2Router02.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/interfaces/IUniswapV2Router01.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.6.2;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/interfaces/IUniswapV2Router02.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.6.2;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/libraries/Math.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/libraries/SafeMath.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/libraries/TransferHelper.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.6.0;
^----------------------^
,/Users/edwardmcmillan/bull_bear_dex/contracts/uniswapv2/libraries/UQ112x112.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity =0.6.12;
^----------------------^

Error: Truffle is currently using solc 0.5.16, but one or more of your contracts specify "pragma solidity 0.6.12".
Please update your truffle config or pragma statement(s).
(See https://trufflesuite.com/docs/truffle/reference/configuration#compiler-configuration for information on
configuring Truffle to use a specific solc compiler version.)

Compilation failed. See above.

so as you can see with the truffle-config file and pacake.json file both saying 0.6.12 it still compiles with version 0.5.16.. and i have tried un install, install truffle -g.. solc versions.. and nothing works.. 

Any help would be appreciate... 

## Environment

* Operating System:  MACOS catalina
* Ethereum client:
* Truffle version (`truffle version`): 0.5.16
* node version (`node --version`): 14.15.3
* npm version (`npm --version`): 6.14.9

**Comment by gnidan** [comment]
You have an extra `}` here:
```javascript
    // Useful for private networks
    // private: {
    // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
     }
```

and you need to change a bunch of `;` to `,` to get it to work.

Also, Truffle doesn't use the solc in `package.json`, you can remove that.

Hope this helps!

**Comment by Tedmcm** [comment]
THX! I always miss the little things.. days spent looking for errors instead of whats staring me in the face.. lol... Went through that file again and its working and i got it deployed.. Thx.. Ted
    On Tuesday, 15 June 2021, 00:15:54 GMT-4, gnidan ***@***.***> wrote:  
 
 


You have an extra } here:
    // Useful for private networks
    // private: {
    // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
    // network_id: 2111,   // This network is yours, in the cloud.
    // production: true    // Treats this network as if it was a public net. (default: false)
     }
and you need to change a bunch of ; to , to get it to work.

Also, Truffle doesn't use the solc in package.json, you can remove that.

Hope this helps!

**Comment by gnidan** [comment]
Happy to help spot a stray curly :)
