### ISSUE TITLE
Node module imports throwing compilation errors as of 5.0.35

### ISSUE THREAD

**Issue by alsco77** [trufflesuite/truffle#2377]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

As of 5.0.35, imports from node packages now throw compilation errors. This may or may not be intended behaviour, but it is a breaking change from 5.0.34 compiler - which seems to work just fine. I much prefer to have these imports over relative or absolute paths to the node modules

## Steps to Reproduce

Import a file from OpenZeppelin using `import { ERC20Mintable } from "openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol"`, inherit and implement the constructor in a basic ERC20 token and try to compile the contract

## Expected Behavior

One would expect the contract to compile just fine and utilise the imported library

## Actual Results

```
ParserError: Source "openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol" not found: File import callback not supported
import { ERC20Mintable } from "openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol"
```

## Environment

* Operating System: Pop_OS (Ubuntu 19.04)
* Ethereum client: `ganache-cli 6.7`
* Truffle version (`truffle version`): 5.0.35
* node version (`node --version`): 10.15
* npm version (`npm --version`): 6.8.0

**Comment by CruzMolina** [comment]
Appears to be a bug introduced by #2363 [here](https://github.com/trufflesuite/truffle/pull/2363/files).

**Comment by ashish10677** [comment]
Is this issue still open? I would like to work on it.

**Comment by eggplantzzz** [comment]
@ashish10677 I don't think anyone currently is working on this issue so please feel free! I haven't investigated too much, let me know if you get to the bottom of this.

**Comment by eggplantzzz** [comment]
@alsco77 I actually have no problem importing an openzeppelin contract in my project. I have the following file and it compiles fine on the latest Truffle.
```
pragma solidity >=0.4.25 <0.6.0;

import "./ConvertLib.sol";
import { ERC20Mintable } from "@openzeppelin/contracts/token/ERC20/ERC20Mintable.sol";

contract MetaCoin {
  mapping (address => uint) balances;
  event Transfer(address indexed _from, address indexed _to, uint256 _value);

  constructor() public {
    balances[tx.origin] = 10000;
  }

  function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
    if (balances[msg.sender] < amount) return false;
    balances[msg.sender] -= amount;
    balances[receiver] += amount;
    emit Transfer(msg.sender, receiver, amount);
    return true;
  }

  function getBalanceInEth(address addr) public view returns(uint){
    return ConvertLib.convert(getBalance(addr),2);
  }

  function getBalance(address addr) public view returns(uint) {
    return balances[addr];
  }
}
```
If you can provide an example repo, perhaps, I will try again to duplicate your issue.

**Comment by alsco77** [comment]
Hey @eggplantzzz, thanks for looking into this. I note there have been a few releases since i posted this and the url for the package import in your file seems a bit different (maybe OZ updated their node package). If you can't replicate and nobody else has reported this then chances are it was something on my end

**Comment by eggplantzzz** [comment]
Ok @alsco77, I'm going to go ahead and close this. If you find later that it is something to do with Truffle, then please get back to us and we'll investigate! Thanks!
