### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by daqingsu19** [trufflesuite/truffle#3798]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

I wanted to try out Truffle/Ganache. So I followed 

https://ethereum.org/en/developers/tutorials/create-and-deploy-a-defi-app/

-I am having version issues with Truffle. This is what "truffle version" shows:
Truffle v5.1.66 (core: 5.1.66)
Solidity - 0.7.4 (solc-js)
Node v15.5.1
Web3.js v1.2.9
I specified solc 0.7.4 in truffle-config.js because the openzeppelin that I use asks for pragma between 0.6 and 0.8.
I specified "pragma solidity >=0.4.22 <0.9.0;" in my contracts. But when I do "truffle compile", I got this:

Compiling your contracts...
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Downloading compiler. Attempt #1.
TypeError: Cannot read property 'imports' of undefined
at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.1.66 (core: 5.1.66)
Node v15.5.1

Seems like I am not able to make truffle, solidity, and openzeppelin all happy wrt versions.

**Comment by Eliseowzy** [comment]
I also have the same problem

**Comment by xternet** [comment]
Downgrade truffle to: **5.1.65**
Set contracts and **_truffle-config.js_** solc version to: `>=0.6.0 <0.8.0`

**Comment by daqingsu19** [comment]
> Downgrade truffle to: **5.1.65**
> Set contracts and **_truffle-config.js_** solc version to: `>=0.6.0 <0.8.0`

Yes downgrading to 5.1.65 works. Thanks a lot!

**Comment by Eliseowzy** [comment]
> Downgrade truffle to: **5.1.65**
> Set contracts and **_truffle-config.js_** solc version to: `>=0.6.0 <0.8.0`

Thank you sooooo much!😀

**Comment by zacel** [comment]
Thank you for this solution but why did you close the issue? it seems like if downgrading to a older version is the fix then it should still be open because it's still broken in 5.1.66 which is what new people will install by default

**Comment by khushjammu** [comment]
I'm having a similar issue. The initial build of my contracts works fine (when artifacts folder is empty). However, every subsequent time I try to `truffle compile`, I get a weird error.

```
Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
```

I'm attempting to build with `solc` version 0.8.1

**Comment by fernandezpaco** [comment]
Same problem here

**Comment by ehildenb** [comment]
We had the same issue, commenting here to track progress.

**Comment by jha-prateek** [comment]
Downgrade doesn't work

![image](https://user-images.githubusercontent.com/21065903/107977773-b16d7f00-6fe1-11eb-8797-4853bcf4a510.png)

**Comment by jha-prateek** [comment]
> I'm having a similar issue. The initial build of my contracts works fine (when artifacts folder is empty). However, every subsequent time I try to `truffle compile`, I get a weird error.
> 
> ```
> Compiling your contracts...
> ===========================
> TypeError: Cannot read property 'imports' of undefined
>     at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
> ```
> 
> I'm attempting to build with `solc` version 0.8.1

have you found any solution to this?

**Comment by zacel** [comment]
I have been getting the same error and found 2 solutions. First is to use a older solidity version (it works for me with 0.6.6) or to use a different tool then truffle (like hardhat)

**Comment by jha-prateek** [comment]
> I have been getting the same error and found 2 solutions. First is to use a older solidity version (it works for me with 0.6.6) or to use a different tool then truffle (like hardhat)

I tried with Truffle v5.1.65 (core: 5.1.65) and Solc 0.6.6, but nothing works🤯

**Comment by zacel** [comment]
for me I had to delete truffle globally, delete node_modules in my project and then after reinstalling everything it worked

**Comment by sofianeOuafir** [comment]
downgrading to 5.1.65 worked for me. curious to know why 5.1.66 didn't work

**Comment by jha-prateek** [comment]
`truffle compile --all`

This works

**Comment by Eliseowzy** [comment]
- Actually, I came to this trouble when I was testing my project, when I tried the command `truffle test` it just showed off this error:

> Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined...
- I reinstalled Truffle: `npm install –g truffle@~5.1.65`
- The OS of my device is Windows 10, and truffle, solidity and node.js versions are as follows: 
> Truffle v5.1.65 (core: 5.1.65)
Solidity v0.5.16 (solc-js)
Node v12.16.1
- Then I declared `pragma solidity ^0.5.16;` at the begining of every contract. I also modified the `fruffle-config.js` file of the project into:
```java script
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    },
    develop: {
      port: 8545
    }
  },
  compilers: { //I added this parameter.
    solc: {
      version: "0.5.16"
    }
  }
};
```
- Then under the project root directory(`project_name/`): I tried the command`truffle test` again, it worked for me.

**Comment by ehildenb** [comment]
Downgrading to 5.1.65 worked for me.

**Comment by snwokenk** [comment]
@jha-prateek answer of using "truffle compile --all" worked for me.

It seems most are making changes or adding new contracts and forgetting to recompile

**Comment by haltman-at** [comment]
OK, it seems a lot of people are having this problem.  Does anyone have a reproduction example we could check out?  Otherwise I'll attemtp to reproduce this myself, but I'm hoping someone has an example I can use directly.  Thank you!

**Comment by haltman-at** [comment]
I have a suspicion that PR #3802 might fix this problem.  However, I really need a reproduction example to be able to check...

**Comment by sshmaxime** [comment]
Try to delete your build folder, it worked for me.

**Comment by ehildenb** [comment]
Reproduction:

```
git clone 'https://github.com/runtimeverification/firefly-demo'
cd firefly-demo
npm install
npm install ganache-cli
```

In one terminal:

```
./node_modules/.bin/ganache-cli -p 8145
```

In another terminal:

```
./node_modules/.bin/truffle test
```

Results in this error:

```
Using network 'development'.


Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/home/dev/src/firefly-demo/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/dev/src/firefly-demo/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.1.66 (core: 5.1.66)
Node v10.23.0
```

Downgrading to 5.1.65 and the error goes away and tests run successfully.

I'm on Node 10.23.0, if it matters.

**Comment by haltman-at** [comment]
@ehildenb Thanks!  I'll check it out.

**Comment by haltman-at** [comment]
Hm, I can't seem to reproduce this at the moment.  I'll have to try some more combinations later, I guess.  That said, I have a suspicion that #3802 might fix this anyway...

**Comment by jha-prateek** [comment]
> @jha-prateek answer of using "truffle compile --all" worked for me.
> 
> It seems most are making changes or adding new contracts and forgetting to recompile

Yes, but it's strange because `truffle compile` should work even without using `--all` flag. [Truffle docs](https://www.trufflesuite.com/docs/truffle/reference/truffle-commands) says `--all: Compile all contracts instead of only the contracts changed since last compile.`

**Comment by jha-prateek** [comment]
> Hm, I can't seem to reproduce this at the moment. I'll have to try some more combinations later, I guess. That said, I have a suspicion that #3802 might fix this anyway...

Can you check, how `truffle compile --all` is working and not `truffle compile`. This might help you in finding the problem. 😀

**Comment by haltman-at** [comment]
Ah, good point.  I'd been compiling from scratch.  But, the example given by @ehildenb above also involves compiling from scratch.  So that doesn't help.  Does anyone have a more specific reproduction example I could try, including which contracts to compile in what order?

**Comment by haltman-at** [comment]
OK, could people retry this with 5.1.67 and see if there's still a problem?  Thanks all!

**Comment by RedCuckoo** [comment]
@haltman-at 

I confirm that upgrading to 5.1.67 solved it for me, using the example provided [here](https://docs.microsoft.com/en-us/learn/modules/blockchain-solidity-ethereum-smart-contracts/5-write-contract).

SIDE NOTE:
This example only compiles successfully, but I can not deploy this contract. Can't find the issue. 

Providing output:

<pre><code>[Execute command]
3_deploy_contracts.js
=====================
[Execute command]
[Execute command] Error: Migration LAPTOP\solidity_project\migrations\3_deploy_contracts.js invalid or does not take any parameters
    at Migration._load (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:49:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration.run (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:171:1)
    at Object.runMigrations (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:262:1)
    at Object.run (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:227:1)
    at Command.run (USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
[Execute command] Truffle v5.1.67 (core: 5.1.67)
Node v14.15.3
[Execute command] Finished running command
[Azure Blockchain] Deploy failed</pre></code>

**Comment by RedCuckoo** [comment]
> SIDE NOTE:
>This example only compiles successfully, but I can not deploy this contract. Can't find the issue.
UPD: I did a stupid error by not saving edited file using Visual Studio Code, so it was trying to deploy an empty file probably. The example is working.

**Comment by cds-amal** [comment]
Oh gosh, @haltman-at , I think I'm running into this issue while running `truffle test`. Interestingly, it fails on my Arch machine and works on OS X.

```
╰─$ truffle test

Compiling your contracts...
===========================
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/ReentrancyAttack.sol
> Compiling ./contracts/ReentrancyGuard.sol
> Compiling ./contracts/ReentrancyMock.sol
> Compiling ./test/TestGuard.sol
> Artifacts written to /tmp/test--1004680-D92aN45Zb2bp
> Compiled successfully using:
   - solc: 0.8.1+commit.df193b15.Emscripten.clang



  TestGuard
    1) "before all" hook: prepare suite for "testTargetIsInitialized"


  0 passing (169ms)
  1 failing

  1) TestGuard
       "before all" hook: prepare suite for "testTargetIsInitialized":
     TypeError: Cannot read property 'imports' of undefined
      at Object.<anonymous> (/home/amal/work/truffle/packages/compile-common/src/profiler/requiredSources.ts:128:45)
      at Generator.next (<anonymous>)
      at fulfilled (/home/amal/work/truffle/packages/compile-common/dist/src/profiler/requiredSources.js:5:58)

```
The debug trace shows `getImports` behaving differently, with `[__Truffle__NotFound.sol]` on failing Arch, and `[]` for OS X.
### Arch
```
2021-02-21T02:20:04.842Z compile-common:profiler:resolveAllSources resolveAllSources called
2021-02-21T02:20:04.848Z compile-common:profiler:getImports filePath: /home/amal/dev/txlog/reentrant/contracts/Migrations.sol
2021-02-21T02:20:04.859Z compile-common:profiler:getImports imports: [ '__Truffle__NotFound.sol' ]
```

### OSX
```
2021-02-21T02:20:48.526Z compile-common:profiler:resolveAllSources resolveAllSources called
2021-02-21T02:20:48.536Z compile-common:profiler:getImports filePath: /Users/cds/dev/txlog/reentrant/contracts/Migrations.sol
2021-02-21T02:20:48.558Z compile-common:profiler:getImports imports: []
```

**Comment by haltman-at** [comment]
OK, I'm going to close this for now then as it appears to be fixed in 5.1.67.  If there's still a problem here we can reoepn this.

**Comment by elranu** [comment]
Hi,
    I still have the problem on version 5.1.67. I have created a repo with the code to reproduce it: https://github.com/elranu/truffle-compile-error

```
PS C:\Dev\repos\gsn-demo2> truffle compile

Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (C:\Users\mvica\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\mvica\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42)
Truffle v5.1.67 (core: 5.1.67)
Node v14.15.1
```

**Comment by haltman-at** [comment]
OK, thanks, I'll check it out!

**Comment by haltman-at** [comment]
OK, I still can't reproduce this. :-/  I had to fix up the example a bit to make it compile -- turning up the version to 0.6.9, fixing the `BaseRelayRecipient` import in `MetaCoin`, installing `@openzeppelin/contracts` and marking `MetaCoin` as abstract -- but once I did it compiled just fine.  I'm not sure what's going on here.

**Comment by elranu** [comment]
@haltman-at do not fix it. Just `clone`, `yarn`, and `truffle compile`. I know it does not compile. But instead of getting a compilation error, I got the message I sent you before.

**Comment by RedCuckoo** [comment]
> @haltman-at do not fix it. Just `clone`, `yarn`, and `truffle compile`. I know it does not compile. But instead of getting a compilation error, I got the message I sent you before.

When I did what you described I still can't compile it because of the import errors (openzeppelin) and solc version, and I am getting compilations errors, but not the one you have sent. 

Could you, please, provide minimal reproducible setup to check?

**Comment by elranu** [comment]
@RedCuckoo 
I just test it again. And probably is something of my environment. The strange thing is with older versions works fine.
My environment is windows 10, npm install truffle,  Truffle v5.1.67 (core: 5.1.67). Node v14.15.1. Really I don´t know what else I can add.

**Comment by haltman-at** [comment]
@elranu Ah, I see, I did not get that error when compiling it without fixing it; I got ordinary compilation errors.  So, I was unable to reproduce it that way either.  I can try seeing if the version of Node is relevant, I suppose.  If it's a Windows-specific problem that will be harder to test.

**Comment by haltman-at** [comment]
OK, using Node 14.15.1 didn't change anything on my end, I'm afraid.  @elranu, just to be sure, are you absolutely certain that you properly uninstalled Truffle 5.1.66 and installed 5.1.67?  (As always, we recommend upgrading via
```
npm uninstall -g truffle
npm install -g truffle
```
to prevent any problems.)  Or are you sure that you don't possibly have two different versions of Truffle installed, say one globally and one locally?  I realize this may be a stupid question, but I want to be certain here...

**Comment by elranu** [comment]
Hi @haltman-at. Thank you very much for your response.
You can check in the repo I sent you, which does not have package.json with a local version. So I don't think it may be that.

Before I was working with version Truffle v5.1.56 and I have upgraded to 5.1.67. That´s the only difference I see.  As you quoted I have use installed and uninstalled. What I did not do, is npm clean cache and restart the computer. I´ll do it soon, sorry. I have a deadline. I´ll let you know.

Thank you very much for all the help. You are amazing guys!

Regards,
Mariano Vicario

**Comment by stebou** [comment]
Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.2.1 (core: 5.2.0)
Node v15.10.0



Hello, i have the same problem with a recent version of truffle .

**Comment by francovilla** [comment]
Same error
Truffle v5.2.2
Solidity 0.6.12
Node v14.15.1
Web3.js v1.2.9

**Comment by photonized** [comment]
Getting the same error when running `truffle test`:

```===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.2.3 (core: 5.2.3)
Node v15.4.0
```

This is on MacOS 11.2.2.

You can reproduce it by following the steps here up until you finish testAdoption.test.js and run `truffle test` for the first time.

**Comment by haltman-at** [comment]
@photonized Hm, so it's not Windows-specific, then.

I don't think the change to the config file is relevant, nor the particular pragmas.  I think the real reason that making that change caused the problem to go away is that, by updating every source file, you caused the profiler to attempt to compile everything; and we know the problem doesn't occur when compiling everything.

But, I'll see if I can reproduce the problem with your example.  I've had no luck with any of the others, but maybe this time will be different...

**Comment by haltman-at** [comment]
@photonized Sorry, did you leave something out?  It seems like you intended to include reproduction steps, but there aren't any there.  Was your "here" supposed to be a link?  Thank you!

**Comment by haltman-at** [comment]
OK, I'll have to try that out later, thanks!

**Comment by haltman-at** [comment]
OK, unfortunately I was still unable to reproduce the problem in this fashion.  Sorry.

**Comment by RobertoDonPedro** [comment]
FYI, I had the same problem, I fixed it by using sudo to uninstalled the old truffle version and to install the latest truffle version V5.2.3 as follows:
```
sudo npm uninstall -g truffle
sudo npm install truffle -g
```
```
truffle compile

Compiling your contracts...
===========================
.....
> Compiled successfully using:
   - solc: 0.6.12+commit.27d51765.Emscripten.clang
```


`truffle version`
```
Truffle v5.2.3 (core: 5.2.3)
Solidity - 0.6.12 (solc-js)
Node v12.21.0
Web3.js v1.2.9
```

**Comment by flcoder** [comment]
I'm using Truffle v5.2.3 and I can't compile due to this error.

**Comment by RobertoDonPedro** [comment]
> I'm using Truffle v5.2.3 and I can't compile due to this error.

did you use sudo?

**Comment by flcoder** [comment]
> > I'm using Truffle v5.2.3 and I can't compile due to this error.
> 
> did you use sudo?

I doubt it.  I avoid sudo unless I have no other option.

**Comment by joequant** [comment]
I ran into the same problem, but when I recompiled with a completely clean repo, I got an error about an unlinked library.

This seems to have something to do with an async not returning a value creating an undefined that propagates down the code.

**Comment by eggplantzzz** [comment]
By the way, you really shouldn't be using `sudo` with Truffle. Ideally you would use npm with nvm and install Truffle that way. You will be a lot less likely to get weird errors. npm itself recommends using npm this way. See [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

I doubt this will resolve this error, but who knows?

**Comment by eggplantzzz** [comment]
@elranu For the record I also cannot duplicate your error using your repo and the steps provided. I just get Solidity compilation errors.

**Comment by rocketengin** [comment]
I was getting the same error but generally have found that a lot of the truffle errors I run into, tie back to the node version. 

I moved from v10.23 to v15.8 and it resolved the problem.

**Comment by joequant** [comment]
@tyler Can you post what errors you are getting?  The thing that I've
noticed is that when I run into this
errors, a clean refresh with a clean repo usually fixes it, but there is an
standard compile error at the end.

The trouble is that I've been so busy trying to get it working that I
haven't tracked exactly which error.

I have a strong suspicion that this is a race condition.  That there is an
error that is properly handled for most
people but if the phase of the moon is wrong then something doesn't get
trapped/initialized and it breaks.

**Comment by eggplantzzz** [comment]
I get standard Solidity compilation errors which I would expect based on looking at the project. I'll screenshot it below - again, these are errors that I would expect from Solidity given the state of the project at clone time.

<img width="1440" alt="Screen Shot 2021-03-18 at 10 17 03 AM" src="https://user-images.githubusercontent.com/14827965/111640982-1a0f6d80-87d3-11eb-94e6-35b8fa72253e.png">

**Comment by fainashalts** [comment]
@eggplantzzz @haltman-at I faced this error as well just now. So it has been reproduced by someone at Truffle now! 

For me, everything compiled fine until I added tests. Once my test was added, I got this same error -- happens on `truffle compile` and `truffle test`. Switching from Node 10 to Node 12 did not fix it. Downgrading versions also did not fix it. 

This is the error: 
```
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)

```

Happy to show this to you tomorrow! I haven't had a chance to dig in to what's causing it but would love to discuss.

**Comment by haltman-at** [comment]
OK, I've just merged #3933, which hopefully should fix this for real.  It'll go out in next week's release!

**Comment by haltman-at** [comment]
OK, #3933 is now released, so I'm going to close this, but please let us know if this error is still happening and we can reopen this!

**Comment by Soohan-Park** [comment]
> Try to delete your build folder, it worked for me.

Cool, It's work for me :)
solc 0.8.0 + truffle 5.1.66

**Comment by lawrenceCP** [comment]
@haltman-at @eggplantzzz 

I am still hitting the same error after attempt with Truffle 5.1.66 and solc 0.8.0.

I tried downgrading truffle to 5.1.65 and using Node 10.23.0, it returns me the same error.

I tried with the latest truffle version seems like the issue still persists.

Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42) 
Truffle v5.3.0 (core: 5.3.0)
Node v14.16.0

Let me know if I can be of any help.

**Comment by Soohan-Park** [comment]
> @haltman-at @eggplantzzz 
> 
> I am still hitting the same error after attempt with Truffle 5.1.66 and solc 0.8.0.
> 
> I tried downgrading truffle to 5.1.65 and using Node 10.23.0, it returns me the same error.
> 
> I tried with the latest truffle version seems like the issue still persists.
> 
> TypeError: Cannot read property 'imports' of undefined
>     at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42) 
> Truffle v5.3.0 (core: 5.3.0)
> Node v14.16.0
> 
> Let me know if I can be of any help.

have you try deleting build folder?

**Comment by lawrenceCP** [comment]
> > @haltman-at @eggplantzzz
> > I am still hitting the same error after attempt with Truffle 5.1.66 and solc 0.8.0.
> > I tried downgrading truffle to 5.1.65 and using Node 10.23.0, it returns me the same error.
> > I tried with the latest truffle version seems like the issue still persists.
> > TypeError: Cannot read property 'imports' of undefined
> > at Object. (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
> > at Generator.next ()
> > at fulfilled (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42)
> > Truffle v5.3.0 (core: 5.3.0)
> > Node v14.16.0
> > Let me know if I can be of any help.
> 
> have you try deleting build folder?

Yup. I deleted and recompile the folder and test it each time I use a different version.. but hit into this error (with different version denote below) when i run truffle test... anyone hit the same issue as per mine?

**Comment by haltman-at** [comment]
@lawrenceCP Are you still getting the error with Truffle 5.3.0?  Could you confirm that?  Thank you!

@Soohan-Park To be clear, deleting the build folder (or just using `truffle compile --all`, which I think would be easier) is a workaround; it's not something we want people to have to do!  If the error is occurring, we want a clear reproducible example so that we can fix it, not for people to just resort to deleting their build folder!

**Comment by lawrenceCP** [comment]
@haltman-at  yes, after tried delete the build folder (or run truffle compile --all) then run truffle test. I am still hitting the error with Truffle 5.3.0.

TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42) 
Truffle v5.3.0 (core: 5.3.0)
Node v14.16.0

Which node version is the recommended version?

**Comment by haltman-at** [comment]
@lawrenceCP OK, do you have some sort of reproduction example I could check out to figure out what's going on?  Thanks!  (I'll reopen the issue.)

We currently support Node 10, Node 12, and Node 14, although we may be dropping support for Node 10 in a few months.

**Comment by lawrenceCP** [comment]
@haltman-at lets try this:
1) git clone https://github.com/lawrenceCP/testTruffle.git
2) cd testTruffle
3) truffle compile --all
4) truffle test

Then you should be able to get an error similar to this.

TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:98:1)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-common\dist\src\profiler\requiredSources.js:5:42) 
Truffle v5.3.0 (core: 5.3.0)
Node v14.16.0

**Comment by eggplantzzz** [comment]
To provide another data point here, @lawrenceCP I cloned your repo and had to fix a couple of imports. In `TestAdoption.sol` you had `import "truffle/Deployment.sol` where it should have been `import/DeployedAddresses.sol`. I also had to correct `assert.equal` to `Assert.equal`. After this `truffle test` ran without any errors. I ran it with Truffle 5.3.0 using both Node 10 and 12.

Is it possible that you have other files in your repo that are not being committed or something?

**Comment by lawrenceCP** [comment]
@eggplantzzz Thanks for the tips. After changing the import statement from import "truffle/Deployment.sol to import "truffle/DeployedAddresses.sol"

as well as the Assert.equal statement, I managed to run truffle test without errors.

@haltman-at may proceed to close off this issue. Thanks.

**Comment by haltman-at** [comment]
@eggplantzzz I don't think that resolves this issue.  Truffle shoud not produce errors, regardless of whether their imports are correct or not.  If they have incorrect imports, they should see a compile error, not a Truffle error!

**Comment by joequant** [comment]
FYI.  I'm stil seeing the issue, but it's happening less than before, and
seems to go away if I delete the build directory.

**Comment by eggplantzzz** [comment]
@haltman-at I didn't say it solves the original issue by the original poster. I am merely saying that after correcting the errors I listed, I am able to run `truffle test` without any errors: parser errors, compiler errors, or otherwise.

**Comment by staringispolite** [comment]
I got this same error for a seemingly unrelated problem: I was missing a } in the newest contract I had just added

deleted /build
ran `truffle compile --all`
got me a slightly more helpful error: "FILENAME_HERE.sol:LAST_LINE_OF_FILE:1: ParserError: Function, variable, struct or modifier declaration expected."

realized/fixed the mistake
ran `truffle compile --all`
compiled successfully

**Comment by MatthewDHarrison** [comment]
I had this error too, got the undefined imports message only when running "truffle test" but not "truffle compile". 
What worked for me: 
 - deleting build folder
 - downgrading from v5.1.67 to v5.1.65
 - making sure import statements were correct (i.e. "truffle/Assert.sol" instead of "truffle/assert.sol")

The version of solidity didn't seem to matter, got it to work with 0.5.16 and >=0.8.0

**Comment by haltman-at** [comment]
@lawrenceCP OK, I have successfully reproduced the error!  Thanks so much for the example, sorry for taking so long to get back to this; I've had my hands pretty full.  But now I can look into what's causing this and hopefully fix it.

**Comment by gideongrinberg** [comment]
This is still broken on the latest version and 0.5.15. Getting truffle to work with solc has just been painful.

**Comment by haltman-at** [comment]
@gideongrinberg A fix for this (or what should be a fix for this) will go out with this week's release!

**Comment by gideongrinberg** [comment]
> @gideongrinberg A fix for this (or what should be a fix for this) will go out with this week's release!

@haltman-at is there any temporary fix?

**Comment by haltman-at** [comment]
Well, as other commenters have mentioned, the error doesn't occur when recompiling the whole project.  But, if you can wait just a few hours a proper fix should go out in today's release, as mentioned, so any temporary workaround will be quite temporary indeed. :)

**Comment by haltman-at** [comment]
The fix for this should be out now, so I'm closing this once again.  If anyone sees this again, please let us know and we'll reopen it a third time.

**Comment by sjschweber** [comment]
Hey, I am getting this error even with most recent version of truffle ... 

> Error: Truffle is currently using solc >=0.6.0 <0.8.0, but one or more of your contracts specify "pragma solidity ^0.8.0".

I tried multiple solutions provided in this thread (downgrading and changing solc version, and truffle compile --all), but none of them worked.

**Comment by sjschweber** [comment]
@haltman-at can you please re-open this issue

**Comment by haltman-at** [comment]
@sjschweber You're describing an different issue; this issue is about an undefined reference crash, not about being unable to compile due to pragma mismatch.  If you are having an issue with pragma mismatch, you might want to file a new issue for that, but I'd suggest that rather than file an issue for that you might want to start with [talking to our support team](https://trufflesuite.zendesk.com/hc/en-us/requests/new) to make sure this is an actual bug.  Thanks!
