### ISSUE TITLE
Truffle Test Not Working With Solidity v0.4.24

### ISSUE THREAD

**Issue by timbeiko** [trufflesuite/truffle#1817]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Quoted from a [StackOverflow post I opened](https://ethereum.stackexchange.com/questions/68223/truffle-test-issue-with-address-payable-and-compiler-version), and posted here after being asked by @gnidan on Gitter.

> I am trying to run truffle test on an old contract which was written using pragma solidity 0.4.24;. While I am able to deploy the contracts using truffle migrate, I get the following error when running truffle test:

```
Using network 'development'.


Compiling your contracts...
===========================
Error: CompileError: Error parsing truffle/DeployedAddresses.sol: ParsedContract.sol:4:55: ParserError: Expected ',' but got 'payable'
  function Marketplace() public pure returns (address payable) { return 0x6395927945EA39aDD6B1E04144f1e1324B30DeFC; }
                                                      ^-----^
Compilation failed. See above.
    at async.whilst.error (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:369:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:969:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:5222:1)
    at Promise.all.then.results (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:351:1)
    at <anonymous>
Truffle v5.0.7 (core: 5.0.7)
Node v8.12.0
```
> `truffle/DeployedAddresses.sol: ParsedContract.sol:4:55` is not code I've written, nor is it part of my project. I suspect this error may be caused because Truffle is running solidity 0.4.24 to compile my contracts but that whatever it uses to execute internal tests is running solidity 0.5. Is there a way to verify/change this?

> Here are the contents of `truffle.js` in the main directory:

```
module.exports = {
  migrations_directory: "./migrations",
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*" // Match any network id
    }, 
 // ... Other configs specified here, removed because irrelevant
 // to SO question ... 
 compilers: {
  solc: {
    version: "0.4.24",  
    }
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 500
    }
  } 
};
```
> and the contents of `truffle.js` under `/test`:

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    }
  }, 
  compilers: {
  solc: {
    version: "0.4.24",  
    }
  }
};
```

While `truffle test` does not work, `truffle migrate` works fine both to deploy locally and to the Rinkeby testnet, so this does not seem to be an error with the Solidity code. Prior to Solidity v0.5.0, the tests ran fine. I considered upgrading my contracts to v0.5.0, but realized they imported several Zeppelin contracts which had `pragma ^0.4.11`.  I had both `.js` and `.sol` tests and neither worked, even when running single files. 

## Steps to Reproduce

1. Write a contract using `pragma 0.4.xx` as the solidity version. 
2. Set the `compilers:solc` version to `0.4.xx` in `truffle.js`
3. Write tests for the contract in (1)
4. Try to run `truffle test` 

**OR**

1. Git clone [this branch](https://github.com/timbeiko/solidity-marketplace/tree/solidity5) for my project
2. Run `truffle test` from inside the main directory

## Expected Behavior

`truffle test` runs the tests.

## Actual Results

See above. 

## Environment

* Operating System: Mac OSx
* Ethereum client: Ganache
* Truffle version (`truffle version`): 
```
Truffle v5.0.7 (core: 5.0.7)
Solidity v0.5.0 (solc-js)
Node v8.12.0
```
* node version (`node --version`): v8.12.0
* npm version (`npm --version`): 6.4.1

**Comment by CruzMolina** [comment]
Hey @timbeiko ! Thanks for raising this. Currently working on a fix 👍

**Comment by CruzMolina** [comment]
Closing as this has been merged via #1820 & released in truffle `5.0.9`

Thanks for raising the issue @timbeiko !

**Comment by timbeiko** [comment]
@CruzMolina just updated and my tests work again 😄 Thank you for the rapid turnaround 💪🏻There are some tests that used to pass but don't anymore, giving messages such as the ones attached, but I'll investigate those separately. 

<img width="582" alt="Screen Shot 2019-03-22 at 9 02 19 AM" src="https://user-images.githubusercontent.com/9390255/54824429-45f9c600-4c81-11e9-8513-d4984d7fdb6d.png">
<img width="426" alt="Screen Shot 2019-03-22 at 9 02 56 AM" src="https://user-images.githubusercontent.com/9390255/54824438-4befa700-4c81-11e9-98b1-75f548932470.png">

**Comment by CruzMolina** [comment]
@timbeiko Great! Yes, there were a couple breaking changes in truffle v5, particularly in regards to tests.

Those errors in particular seem to be in regards to changes to web3 1.0 0x bytes representation & a change to the revert error message.

If anything suspicious comes up, feel free to comment or open up another issue!
